import test from 'node:test';
import assert from 'node:assert/strict';
import {CollisionWorld,freshState,stepPlayer,decodeSave,readSave,writeSave,SAVE_KEY,makeResources,interaction,useInteraction,eat} from '../src/game-core.js';
const grid={nx:21,nz:21,x0:-100,z0:-100,dx:10,dz:10};
function world(depth=0,trees){return new CollisionWorld(grid,{bed:new Float32Array(441).fill(3),ground:new Float32Array(441).fill(3),depth:new Float32Array(441).fill(depth)},trees);}
const fresh=()=>freshState(1741,{x:0,y:3.02,z:0});
test('save roundtrip preserves needs, inventory and depleted resources; invalid files fail',()=>{const s=fresh();s.berries=4;s.elapsed=45;s.harvested['berry-1']=190;const map=new Map(),storage={setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k)};writeSave(storage,s);const decoded=readSave(storage);assert.equal(decoded.save.berries,4);assert.equal(decoded.save.harvested['berry-1'],190);assert.equal(decoded.save.player.thirst,85);assert.throws(()=>decodeSave('{broken'));assert.throws(()=>decodeSave(JSON.stringify({...s,version:99})));assert.throws(()=>decodeSave(JSON.stringify({...s,player:{...s.player,x:Infinity}})));storage.setItem(SAVE_KEY,'{}');assert.equal(readSave(storage).save,null);assert.ok(readSave(storage).error);assert.throws(()=>writeSave({setItem(){throw Error('quota');}},s),/quota/);});
test('walking uses seconds, normalizes diagonals, and remains grounded',()=>{const a=fresh(),b=fresh(),w=world();for(let i=0;i<60;i++){stepPlayer(a,w,{x:1,z:0},1/60);stepPlayer(b,w,{x:1,z:1},1/60);}assert.ok(Math.abs(a.player.x-3.1)<.001);assert.ok(Math.abs(Math.hypot(b.player.x,b.player.z)-3.1)<.001);assert.equal(a.player.y,3.02);});
test('jump leaves ground, lands, and cannot retrigger in the air',()=>{const s=fresh(),w=world();stepPlayer(s,w,{jump:true},1/60);const vy=s.player.vy;assert.ok(s.player.y>3.02);stepPlayer(s,w,{jump:true},1/60);assert.ok(s.player.vy<vy);for(let i=0;i<120;i++)stepPlayer(s,w,{},1/60);assert.equal(s.player.grounded,true);assert.equal(s.player.y,3.02);});
test('capsule blocks high steps and resolves tree trunks',()=>{const w=world(),s=fresh();w.height=(x)=>x>1?5:3;w.slope=()=>[0,0];for(let i=0;i<120;i++)stepPlayer(s,w,{x:1},1/60);assert.ok(s.player.x<1);const forest=world(0,new Float32Array([0,3,0,15]));const [x,z]=forest.resolveTrunks(0,0,3);assert.ok(Math.hypot(x,z)>.59);});
test('steep slope prevents uphill walking; deep water supports swimming',()=>{const w=world(),s=fresh();w.height=(x)=>3+x;w.water=()=>-Infinity;w.slope=()=>[1,0];for(let i=0;i<60;i++)stepPlayer(s,w,{x:1},1/60);assert.ok(s.player.x<=0);const swim=fresh();swim.player.y=4.1;stepPlayer(swim,world(2),{},1/60);assert.equal(swim.player.swimming,true);assert.ok(Math.abs(swim.player.y-4.1)<.001);});
test('sprint consumes stamina, needs decline, and starvation damages health',()=>{const s=fresh(),w=world();for(let i=0;i<60;i++)stepPlayer(s,w,{x:1,sprint:true},1/60);assert.ok(s.player.stamina<90);assert.ok(s.player.hunger<85);assert.ok(s.player.thirst<85);s.player.hunger=0;for(let i=0;i<60;i++)stepPlayer(s,w,{},1/60);assert.ok(s.player.health<100);});
test('gather once per cooldown, eat consumes inventory, and only freshwater is drinkable',()=>{const s=fresh(),w=world(),r=[{id:'berry-0',x:0,y:3,z:0}];assert.equal(interaction(s,w,r).kind,'gather');useInteraction(s,interaction(s,w,r));assert.equal(s.berries,3);assert.equal(interaction(s,w,r),null);assert.equal(eat(s),true);assert.equal(s.berries,2);s.elapsed=181;assert.equal(interaction(s,w,r).kind,'gather');assert.equal(interaction(s,world(.3),[]).kind,'drink');const sea=world(.3);sea.height=()=>-.3;assert.equal(interaction(s,sea,[]),null);assert.deepEqual(makeResources(w,s.player,1741),makeResources(w,s.player,1741));});
