import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {assembleSources,replaceOnce} from '../src/source-assembly.js';
import {makeGridIndices} from '../src/renderer.js';
import {gridFor,QUALITY} from '../src/quality.js';
const root=new URL('../',import.meta.url);
const text=async p=>readFile(new URL(p,root),'utf8');
const inputs=Object.fromEntries(await Promise.all(Object.entries({coast:'vendor/coast/src/coastal-kernels.cu',coastRender:'vendor/coast/src/coastal-render.cu',river:'vendor/river/src/river.cu',impacts:'vendor/river/src/impacts.cu',grass:'vendor/realgrass/kernels/grass.cu',plant:'vendor/realgrass/kernels/plant-model.cuh',island:'kernels/island.cu'}).map(async([key,file])=>[key,await text(file)])));
const assembly=assembleSources(inputs);
test('source adapters reject missing or ambiguous replacements',()=>{assert.throws(()=>replaceOnce('x','a','b'));assert.throws(()=>replaceOnce('aa','a','b'));assert.equal(replaceOnce('ab','a','c'),'cb');});
test('all upstream systems remain linked, not a replacement ray marcher',()=>{for(const name of ['advectMomentum','limitFlux','commitTransport','riverRock','reconstructRiver','waterfallSpray','shoreProfile'])assert.match(assembly.source,new RegExp('void '+name+'|float '+name));assert.match(assembly.grassSource,/PlantOrgan plant = describeOrgan/);assert.match(assembly.grassSource,/cloudGust/);});
test('only one conservative water state / one surface covers river and sea',()=>{assert.match(assembly.source,/void islandBoundary/);assert.match(assembly.source,/void initializeIsland/);assert.match(assembly.source,/Explicit spring discharge/);assert.match(assembly.source,/closed==0/);});
test('grass roots follow terrain and exclude actual water and rocks',()=>{assert.match(assembly.grassSource,/plant.root.y \+= ground/);assert.match(assembly.grassSource,/depth>\.025f/);assert.match(assembly.grassSource,/bed-ground>\.07f/);assert.match(assembly.grassSource,/float y=r.y\+s.x/);});
test('quality profiles keep the same domain and support finite 120Hz steps',()=>{for(const q of Object.values(QUALITY)){const g=gridFor(q);assert.equal(g.x0,-400);assert.equal(g.z0,-400);assert.equal(g.dx*(g.nx-1),800);assert.ok(q.grass%256===0);assert.ok(g.nx*g.nz*19*4<128*1024*1024);assert.ok((Math.sqrt(9.81*25)+9)/120/g.dx<.3);}});
test('static grid topology is in bounds for all copies',()=>{const a=makeGridIndices(5,7,3);assert.equal(a.length,4*6*6*3);assert.equal(Math.max(...a),5*7*3-1);assert.ok(a.every(v=>v>=0&&v<105));});
test('all 25 precompiled CUDA entry points retain WGSL metadata',async()=>{const artifacts=JSON.parse(await text('generated/kernels.json'));assert.equal(Object.keys(artifacts).length,25);for(const a of Object.values(artifacts)){assert.ok(a.wgsl.includes('@compute'));assert.ok(a.metadata.bindings.length<=8);assert.equal(a.metadata.workgroupSize[1],1);}});
test('browser assets do not require external CDNs or native CUDA',async()=>{const main=await text('src/main.js'),html=await text('index.html');assert.doesNotMatch(main+html,/https?:\/\/|unpkg|jsdelivr|three\.js/);assert.match(html,/src="\.\/src\/main.js"/);});
