// Original Saltreach RGBA noise, generated by its pinned CUDA kernel.
export async function createCoastNoise(sim){
 const d=sim.device,size=512;
 const texture=d.createTexture({label:'Saltreach original material noise',size:[size,size],format:'rgba8unorm',mipLevelCount:10,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});
 const Noise=sim.runtime.createBuffer(size*size*4);
 const binding=sim.kernels.generateNoise.bind({Noise},{size});
 const batch=sim.runtime.batch();batch.dispatch(binding,[size*size/128,1,1]);batch.endPass();
 batch.encoder.copyBufferToTexture({buffer:Noise.gpuBuffer,bytesPerRow:size*4},{texture},[size,size]);batch.submit();
 const sampler=d.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear',addressModeU:'repeat',addressModeV:'repeat'});
 const module=d.createShaderModule({code:`
 @group(0) @binding(0) var tex:texture_2d<f32>;
 @group(0) @binding(1) var smp:sampler;
 struct V{@builtin(position) p:vec4f,@location(0) uv:vec2f}
 @vertex fn vs(@builtin(vertex_index) i:u32)->V{let p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));var v:V;v.p=vec4f(p[i],0,1);v.uv=p[i]*vec2f(.5,-.5)+.5;return v;}
 @fragment fn fs(v:V)->@location(0) vec4f{return textureSampleLevel(tex,smp,v.uv,0.);}`});
 const pipeline=d.createRenderPipeline({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:'rgba8unorm'}]}});
 const encoder=d.createCommandEncoder();
 for(let level=1;level<10;level++){
  const group=d.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:texture.createView({baseMipLevel:level-1,mipLevelCount:1})},{binding:1,resource:sampler}]});
  const pass=encoder.beginRenderPass({colorAttachments:[{view:texture.createView({baseMipLevel:level,mipLevelCount:1}),loadOp:'clear',storeOp:'store'}]});pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.draw(3);pass.end();
 }
 d.queue.submit([encoder.finish()]);await sim.runtime.idle();sim.runtime.destroyBuffer(Noise);
 return {texture,view:texture.createView(),sampler};
}
